### ISSUE TITLE
error at compile

### ISSUE THREAD

**Issue by McColdewey** [cliviu74/onewire-prom-exporter#4]
When I get this error when calling build.sh:

> ./main.go:65:28: undefined: prometheus.Handler

I'm completely new to go. What am I doing wrong?

**Comment by cliviu74** [comment]
Hey, can you tell me what OS are you building on and what version of GO have you installed?

**Comment by cliviu74** [comment]
Fix issues, please have a go and see if that fixes the problem.

**Comment by McColdewey** [comment]
Thank you! The change fixes the problem, it now compiles fine. J
